# REQUIRED for GitHub Pages project sites
baseurl: "/portfolio-draft-101"
url: "https://iamomardarwesh.github.io"

# If you're not using Jekyll theme, keep this empty
theme: null

# Optional â€“ prevents future Jekyll errors
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock

markdown: kramdown
kramdown:
  input: GFM
