title: ""

emote_theme: "bradleyshaw/slate-and-simple"

plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Optional: Font customization (Google Fonts)
font:
  body: "Georgia, serif"     # body text font
  heading: "Helvetica, sans-serif"  # header font








